=== dgading/data-catalog-admin/schemas/comment.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "Comment",
  "description": "A comment that has been applied to an entity like a dataset.",
  "type": "object",
  "required": [
    "title",
    "created",
    "modified",
    "body",
    "identifier"
  ],
  "properties": {
    "title": {
      "title": "Title",
      "type": "string"
    },
    "parent": {
      "title": "parent",
      "type": "string",
      "faker": "random.uuid"
    },
    "identifier": {
      "type": "string",
      "title": "Identifier",
      "faker": "random.uuid"
    },
    "created": {
      "type": "string",
      "title": "Created",
      "format": "date-time"
    },
    "modified": {
      "type": "string",
      "title": "Modified",
      "format": "date-time"
    },
    "body": {
      "type": "string",
      "title": "body",
      "faker": "lorem.sentences"
    }
  }
}

=== dgading/data-catalog-admin/api/comment/820a8dc0-74dc-4b3c-9209-5c90aa700bbc.json
{
  "title": "adipisicing temp",
  "created": "1953-09-05T14:45:47.011Z",
  "modified": "1941-06-18T00:26:24.955Z",
  "body": "Quibusdam natus eaque officiis molestiae assumenda. Rerum quos nam et laborum iure deserunt quae. Totam voluptatem aperiam nesciunt fuga consectetur. Odit laboriosam officiis nulla repudiandae beatae omnis magnam.",
  "identifier": "820a8dc0-74dc-4b3c-9209-5c90aa700bbc"
}

=== dgading/data-catalog-admin/api/comment/efc47fa1-c0cf-49be-85fb-5a56de3a866b.json
{
  "title": "mollit dolor Lorem voluptate velit",
  "created": "1982-01-26T17:58:33.242Z",
  "modified": "1998-02-22T20:29:40.930Z",
  "body": "Similique assumenda numquam. Qui veniam consequatur neque velit sit autem. Dolores veniam eum voluptas voluptatem laborum. Omnis qui occaecati sapiente dignissimos adipisci beatae et mollitia. Nihil assumenda dignissimos et molestias rerum non. Libero aliquam non ea suscipit molestiae quia distinctio quo ad.",
  "identifier": "efc47fa1-c0cf-49be-85fb-5a56de3a866b",
  "parent": "6856e8bf-862f-4b72-8db9-a8f449af22b1"
}

=== dgading/data-catalog-admin/api/comment/27f004fa-dbeb-4eb6-a09a-973f5344f0cb.json
{
  "title": "reprehenderit",
  "created": "1956-11-21T15:09:13.251Z",
  "modified": "1975-07-15T10:30:15.393Z",
  "body": "Sed molestiae quis quia voluptas autem. Enim quod sequi. Ipsam eaque doloribus placeat ab molestias iusto error. Dolorem occaecati sit voluptas vel quas eos suscipit at assumenda. Et voluptatem adipisci.",
  "identifier": "27f004fa-dbeb-4eb6-a09a-973f5344f0cb",
  "parent": "96e64597-8ac2-4ea1-840c-3afa1bf66007"
}

=== dgading/data-catalog-admin/api/comment/79435912-6368-43dd-9baf-9acd2f021ea9.json
{
  "title": "ullamco",
  "created": "1986-10-10T22:23:12.114Z",
  "modified": "1952-03-24T17:46:27.143Z",
  "body": "Ad amet in libero ea sequi. Dignissimos facilis cumque odio quos sed cum libero sit nostrum. Reiciendis ut voluptates. Aut rem amet aut laudantium vel repellat. Sunt dolor non dolores voluptatem. Dolorum rem consequatur modi quaerat sapiente eos.",
  "identifier": "79435912-6368-43dd-9baf-9acd2f021ea9",
  "parent": "d4f625af-a3a5-4c1a-9237-eb3dcec89393"
}

=== dgading/data-catalog-admin/api/comment/898a2914-7dcb-4a9b-8fa2-3a12b1a6718b.json
{
  "title": "Lorem nisi et cillum nostrud",
  "created": "1957-07-14T11:16:00.931Z",
  "modified": "1994-08-09T17:35:32.143Z",
  "body": "Deserunt dolore dolorem rerum impedit. Optio velit nobis dolore ut facere doloribus ex. Et non sunt maxime saepe vel ipsa. Eligendi et illum doloribus et odit eum ipsum nam et.",
  "identifier": "898a2914-7dcb-4a9b-8fa2-3a12b1a6718b",
  "parent": "17bc34b0-c14c-4fcc-8f9c-0de99424b52a"
}

=== dgading/data-catalog-admin/api/comment/3a20ba4f-1230-409e-baa9-790981882e7a.json
{
  "title": "deserunt est",
  "created": "1955-10-26T04:15:55.625Z",
  "modified": "2015-10-19T11:29:07.418Z",
  "body": "Commodi eaque quidem sed nisi necessitatibus ipsum impedit. Nemo et odit. Delectus quia consectetur nihil dolor nostrum. Incidunt expedita explicabo ipsa qui repellat nihil officia culpa eius. Itaque tempore dicta cum accusamus ut minus. Molestias rerum qui aliquid.",
  "identifier": "3a20ba4f-1230-409e-baa9-790981882e7a"
}

=== dgading/data-catalog-admin/api/comment/9e0cd3c1-d222-4eb4-870a-97eaa1d9bc07.json
{
  "title": "irure veniam",
  "created": "2001-06-23T19:33:25.986Z",
  "modified": "1939-12-11T11:52:31.529Z",
  "body": "Aliquid illo et adipisci accusantium rerum excepturi blanditiis et illo. Harum consequuntur eligendi rerum perferendis vel eligendi.",
  "identifier": "9e0cd3c1-d222-4eb4-870a-97eaa1d9bc07",
  "parent": "7695546c-c44e-4152-aa2d-d281fba5e90b"
}

=== dgading/data-catalog-admin/api/comment/c1323596-60ce-4947-862b-c0506629b246.json
{
  "title": "voluptate minim in",
  "created": "1939-10-14T14:51:13.308Z",
  "modified": "2001-06-30T01:02:43.116Z",
  "body": "Vel quo omnis fugit. Et fugiat perferendis provident rerum cum natus. Numquam aut laudantium. Dolor sed id neque ex maiores odit est vero. Molestias et totam laboriosam id.",
  "identifier": "c1323596-60ce-4947-862b-c0506629b246"
}
