=== dgading/data-catalog-admin/schemas/comment.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "Comment",
  "description": "A comment that has been applied to an entity like a dataset.",
  "type": "object",
  "required": [
    "title",
    "created",
    "modified",
    "body",
    "identifier"
  ],
  "properties": {
    "title": {
      "title": "Title",
      "type": "string"
    },
    "parent": {
      "title": "parent",
      "type": "string",
      "faker": "random.uuid"
    },
    "identifier": {
      "type": "string",
      "title": "Identifier",
      "faker": "random.uuid"
    },
    "created": {
      "type": "string",
      "title": "Created",
      "format": "date-time"
    },
    "modified": {
      "type": "string",
      "title": "Modified",
      "format": "date-time"
    },
    "body": {
      "type": "string",
      "title": "body",
      "faker": "lorem.sentences"
    }
  }
}

=== dgading/data-catalog-admin/api/comment/33ca0412-90d9-4424-878d-f9764a35d851.json
{
  "title": "esse veniam exercitation labore non",
  "created": "2018-03-23T06:31:38.077Z",
  "modified": "2017-10-19T01:30:27.295Z",
  "body": "Delectus iste ex in quibusdam. Libero quia in et omnis dicta est necessitatibus cum dignissimos.",
  "identifier": "33ca0412-90d9-4424-878d-f9764a35d851",
  "parent": "17f30fa2-c537-4685-8cef-6884f79f50b5"
}

=== dgading/data-catalog-admin/api/comment/cf057ec6-34c1-4c5f-9303-4687ead9fe9f.json
{
  "title": "sed Duis anim",
  "created": "2014-02-19T12:10:03.788Z",
  "modified": "1971-07-20T08:41:16.136Z",
  "body": "Omnis quod amet magnam libero architecto et nemo. Fuga a qui natus dolorem minima cupiditate dolore. Dolores soluta quae cum aut unde. Tenetur architecto consequatur sed consectetur ut et possimus illum dignissimos.",
  "identifier": "cf057ec6-34c1-4c5f-9303-4687ead9fe9f"
}

=== dgading/data-catalog-admin/api/comment/eb501728-8918-4ed7-94e4-a4737aeca6f2.json
{
  "title": "ut do laborum dolor",
  "created": "1954-05-01T23:03:36.710Z",
  "modified": "1986-10-21T18:39:15.539Z",
  "body": "Ipsa omnis consequatur nam neque voluptate deserunt est aut. Consequatur eum eius rerum reiciendis provident est consequatur. Suscipit sit facere fugit molestias. Quo voluptatem id aut. Reprehenderit totam animi sint necessitatibus ex. Qui commodi sit voluptas nemo qui quam itaque.",
  "identifier": "eb501728-8918-4ed7-94e4-a4737aeca6f2"
}

=== dgading/data-catalog-admin/api/comment/a74f0082-dda5-47be-ae39-aa6e45aaa96b.json
{
  "title": "ex elit minim",
  "created": "2007-10-19T01:46:25.428Z",
  "modified": "1942-01-03T14:02:14.889Z",
  "body": "Quisquam nihil molestias. Eaque deleniti sapiente. Velit occaecati dignissimos architecto. Tenetur aspernatur non distinctio sint. Necessitatibus animi nihil.",
  "identifier": "a74f0082-dda5-47be-ae39-aa6e45aaa96b",
  "parent": "22759a97-b819-4304-903c-cc2a7754a81e"
}

=== dgading/data-catalog-admin/api/comment/c890093a-4cb4-45c0-93a9-599e081ba47c.json
{
  "title": "ex",
  "created": "1981-04-26T08:26:40.564Z",
  "modified": "1958-09-16T06:55:52.769Z",
  "body": "Nulla et et ducimus. Excepturi minima tempore voluptates. Cupiditate et eligendi quaerat soluta beatae labore et sint nam.",
  "identifier": "c890093a-4cb4-45c0-93a9-599e081ba47c",
  "parent": "8184792f-665e-448a-a0a8-304f8b21e943"
}

=== dgading/data-catalog-admin/api/comment/901bfcb9-84cf-4f4c-bbc5-4775a81f0b74.json
{
  "title": "proident exercitation",
  "created": "1992-11-12T06:14:52.933Z",
  "modified": "1946-01-09T01:44:32.983Z",
  "body": "Perspiciatis tempora consequatur voluptatum. Dolores quaerat quis illum ut ea cumque voluptatum. Placeat atque eos recusandae porro dolorem et magni quis sint. Quis rem sed. Sed perspiciatis omnis consequatur minus illum omnis vero ut.",
  "identifier": "901bfcb9-84cf-4f4c-bbc5-4775a81f0b74"
}

=== dgading/data-catalog-admin/api/comment/9a864324-2f4f-41d1-85aa-e06305551c5d.json
{
  "title": "in sed voluptate",
  "created": "1942-02-26T01:55:10.027Z",
  "modified": "1962-07-21T23:17:18.723Z",
  "body": "Occaecati autem modi earum. Asperiores dolorem molestiae dolores eos est labore voluptates beatae corrupti. Non autem facilis. Quis ea excepturi autem sint quod deserunt.",
  "identifier": "9a864324-2f4f-41d1-85aa-e06305551c5d"
}

=== dgading/data-catalog-admin/api/comment/cd1e7d3f-a16f-4f46-a2e0-05d787fcaf52.json
{
  "title": "ipsum fugiat incididunt est consectetur",
  "created": "1985-11-14T13:11:26.350Z",
  "modified": "2019-01-30T14:54:04.017Z",
  "body": "Voluptas qui accusamus itaque non necessitatibus quo eius debitis cum. Nihil non aut dolorum nostrum aut beatae.",
  "identifier": "cd1e7d3f-a16f-4f46-a2e0-05d787fcaf52"
}
