=== dgading/data-catalog-admin/schemas/comment.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "Comment",
  "description": "A comment that has been applied to an entity like a dataset.",
  "type": "object",
  "required": [
    "title",
    "created",
    "modified",
    "body",
    "identifier"
  ],
  "properties": {
    "title": {
      "title": "Title",
      "type": "string"
    },
    "parent": {
      "title": "parent",
      "type": "string",
      "faker": "random.uuid"
    },
    "identifier": {
      "type": "string",
      "title": "Identifier",
      "faker": "random.uuid"
    },
    "created": {
      "type": "string",
      "title": "Created",
      "format": "date-time"
    },
    "modified": {
      "type": "string",
      "title": "Modified",
      "format": "date-time"
    },
    "body": {
      "type": "string",
      "title": "body",
      "faker": "lorem.sentences"
    }
  }
}

=== dgading/data-catalog-admin/api/comment/fbb7b586-a29c-4698-8fec-9389285448ab.json
{
  "title": "fugiat",
  "created": "1940-12-06T15:31:05.538Z",
  "modified": "2011-06-04T00:19:18.760Z",
  "body": "Qui non sed laboriosam dicta sapiente totam sit. Autem est numquam delectus et. Est laboriosam hic. Impedit nostrum id id ea omnis aliquid hic dolorum. Cumque ea enim odit culpa. Eius reiciendis repellendus aut illo aut corporis.",
  "identifier": "fbb7b586-a29c-4698-8fec-9389285448ab",
  "parent": "b38482b8-6cea-4fc9-a45e-16db59ed95ce"
}

=== dgading/data-catalog-admin/api/comment/751d6f73-881e-4837-91d1-0b5e755a9a1a.json
{
  "title": "eu mollit magna est",
  "created": "1952-11-05T16:43:16.279Z",
  "modified": "1955-03-11T08:16:47.085Z",
  "body": "Dolorem soluta dolorem magnam molestiae at dolor in. Similique molestiae odio. Cum magni pariatur soluta. Et pariatur ut laboriosam excepturi cumque et nostrum. Ea est non dolore.",
  "identifier": "751d6f73-881e-4837-91d1-0b5e755a9a1a"
}

=== dgading/data-catalog-admin/api/comment/90db66f2-daff-4c40-b847-297a0ecdf696.json
{
  "title": "laborum esse",
  "created": "1988-12-30T05:53:46.839Z",
  "modified": "1971-12-27T03:30:34.611Z",
  "body": "Beatae reprehenderit doloribus. Neque iusto inventore libero quaerat. Quo adipisci similique et sunt rerum ea. Earum sit id cumque error est sint dolor.",
  "identifier": "90db66f2-daff-4c40-b847-297a0ecdf696"
}

=== dgading/data-catalog-admin/api/comment/861129ff-7926-43ac-9303-ebe225b30b50.json
{
  "title": "est elit eu sed",
  "created": "1986-02-23T14:46:26.316Z",
  "modified": "2003-09-24T07:41:48.795Z",
  "body": "Rerum vel soluta hic. Hic at fugiat natus qui sit voluptatum aliquam voluptatibus quaerat. Repellendus voluptas facere enim impedit non provident est quaerat. Ipsum non ut. Error tenetur perferendis qui vero odit iusto iure nam.",
  "identifier": "861129ff-7926-43ac-9303-ebe225b30b50"
}

=== dgading/data-catalog-admin/api/comment/bdf39594-95ba-49f3-84e1-0f55f784cd0f.json
{
  "title": "incididunt amet labore consequat",
  "created": "2007-01-05T16:06:55.415Z",
  "modified": "1972-07-27T16:58:55.221Z",
  "body": "Maiores ab quia iusto sapiente quis labore doloribus saepe. Non sit non cupiditate id. Ullam in ut distinctio aut officia vel. Sunt eaque vel et. Voluptatem quis aperiam inventore. Aut dolorum minima est natus magnam illo qui omnis facilis.",
  "identifier": "bdf39594-95ba-49f3-84e1-0f55f784cd0f",
  "parent": "2857dd8e-0327-4b03-ac95-6b71156c7f51"
}

=== dgading/data-catalog-admin/api/comment/932be964-20e0-4c47-9344-05844fd1e990.json
{
  "title": "aliqua occaecat in exercitation mollit",
  "created": "1983-08-03T11:19:08.184Z",
  "modified": "1964-05-23T22:54:44.365Z",
  "body": "Natus voluptas impedit. Aut dolor velit aperiam voluptatum ea. Nobis quo nihil. Aliquid eum cum omnis accusantium ex. Dolores consequatur veniam sed non. Accusamus voluptatem quia omnis ducimus sunt est.",
  "identifier": "932be964-20e0-4c47-9344-05844fd1e990",
  "parent": "7296a20b-17b4-4ecf-bf69-102d98d5c8a3"
}

=== dgading/data-catalog-admin/api/comment/339500b2-193b-4b2f-8f4e-bebbded069cc.json
{
  "title": "aliqua ut",
  "created": "1939-12-10T23:31:35.915Z",
  "modified": "1985-12-07T04:45:37.117Z",
  "body": "Voluptas sed dolor neque iste qui ullam. Qui optio quasi qui est quae enim rerum ut quae. Illum recusandae nesciunt pariatur velit debitis maiores fuga.",
  "identifier": "339500b2-193b-4b2f-8f4e-bebbded069cc"
}

=== dgading/data-catalog-admin/api/comment/df37633e-6191-4315-9805-b164facf0e22.json
{
  "title": "officia dolor est ullamco culpa",
  "created": "1939-08-13T08:32:19.539Z",
  "modified": "2014-08-27T14:51:51.377Z",
  "body": "Deleniti quia autem fuga ullam consequatur commodi rem. Quia deleniti delectus occaecati facere non ut quo enim. Distinctio voluptatum hic quisquam voluptas.",
  "identifier": "df37633e-6191-4315-9805-b164facf0e22",
  "parent": "baf0a202-f703-458b-a3ab-4e54ede3dc0f"
}
